### ISSUE TITLE
searching Sinopia is not finding some characters with diacritics

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_indexing_pipeline#116]
earlier in https://github.com/LD4P/sinopia_indexing_pipeline/issues/53 we improved the Sinopia search so that if you search for a simple character, it finds matches of that character with and without diacritical marks (example: search for `orbita` and results include `Órbita`

however there is at least one example where it looks like Sinopia things a character plus diacritic is actually a character followed by another character:
https://trellis.stage.sinopia.io/https://trellis.stage.sinopia.io/repository/chicago/a75ad20f-7107-48aa-8165-204cec78184a

the title is `Voĭna i mir`
user expects to finds this by searching for `voina` but `voina` gives 0 results

however searching for `voi*` with wildcard finds it, as if `ĭ` were 'i' followed by another character

`voina` should find `Voĭna`

I don't know what other diacritical marks this is happening with

(also, case is not an issue, we have case insensitive search and it's working as expected)

**Comment by justinlittman** [comment]
Odd. Ascii folding seems to handle this correctly:
```
curl -X GET "localhost:9200/_analyze?pretty" -H 'Content-Type: application/json' -d'
> {
>   "tokenizer" : "standard",
>   "filter" : ["asciifolding"],
>   "text" : "Voĭna i mir"
> }
> '
{
  "tokens" : [
    {
      "token" : "Voina",
      "start_offset" : 0,
      "end_offset" : 5,
      "type" : "<ALPHANUM>",
      "position" : 0
    },
    {
      "token" : "i",
      "start_offset" : 6,
      "end_offset" : 7,
      "type" : "<ALPHANUM>",
      "position" : 1
    },
    {
      "token" : "mir",
      "start_offset" : 8,
      "end_offset" : 11,
      "type" : "<ALPHANUM>",
      "position" : 2
    }
  ]
}
```

**Comment by justinlittman** [comment]
Same with both lowercase and ascii folding:
```
curl -X GET "localhost:9200/_analyze?pretty" -H 'Content-Type: application/json' -d'
> {
>   "tokenizer" : "standard",
>   "filter" : ["lowercase", "asciifolding"],
>   "text" : "Voĭna i mir"
> }
> '
{
  "tokens" : [
    {
      "token" : "voina",
      "start_offset" : 0,
      "end_offset" : 5,
      "type" : "<ALPHANUM>",
      "position" : 0
    },
    {
      "token" : "i",
      "start_offset" : 6,
      "end_offset" : 7,
      "type" : "<ALPHANUM>",
      "position" : 1
    },
    {
      "token" : "mir",
      "start_offset" : 8,
      "end_offset" : 11,
      "type" : "<ALPHANUM>",
      "position" : 2
    }
  ]
}
```

**Comment by justinlittman** [comment]
@ndushay recommends https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-folding.html

**Comment by justinlittman** [comment]
Initial work for this ticket: Test icu-folding and see if it addresses this problem.

**Comment by justinlittman** [comment]
After upgrade of dev to ES 6.8, still able to reproduce the problem.

**Comment by justinlittman** [comment]
ICU folding filter did it:
![image](https://user-images.githubusercontent.com/588335/69728207-0f1e5e80-10f2-11ea-918f-5a8584620473.png)

**Comment by justinlittman** [comment]
Downgrading dev to 6.4 and trying again.
