### ISSUE TITLE
Literal values with no associated language aren't indexed

### ISSUE THREAD

**Issue by CECSpecialistI** [LD4P/sinopia_indexing_pipeline#156]
Many literal values, such as catalogerID, don't have a language associated with them. Barcodes, call numbers, identifiers. When I search for resources I've saved in Sinopia, only resources for which I've assigned a language of my catalogerID show up when I search under my cataloger ID. The same is true for call numbers. Search should include literal values which are not associated with a language.

Examples: cataloger ID "cec23" does not pull up description for "Alten Stettin"
Call number "PG3476.C355" does not pull up manifestation or item associated with "Разные звери,Raznye zveri"

**Comment by justinlittman** [comment]
The problem is that we are expecting JSON like:
```
  "mainTitle": {
     "@value": "Hamlet",
     "@language": "eng"
   }
```
but when the language is removed, get:
```
"mainTitle": "Hamlet"
```

This is yet another instance where we are getting burned by treating JSON-LD as JSON. At this point, we need to re-write the indexer to treat it as RDF.

**Comment by michelleif** [comment]
@justinlittman is this the cause of ld4p/sinopia_editor#2090

**Comment by justinlittman** [comment]
Yes.

**Comment by michelleif** [comment]
since #2090 was fixed, is this also fixed?

**Comment by justinlittman** [comment]
Yes
