### ISSUE TITLE
Deploy indexing pipeline

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia_indexing_pipeline#18]
- [x] Create Amazon MQ service
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment
- [x] Create ElasticSearch service 
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment
- [x] Create ECS service for pipeline (using `ld4p/sinopia_indexing_pipeline` container and no explicit `command` stanza)—**note** that this service depends on Trellis, ES, and MQ, and won't start without them, so the above steps (per env) must be done before this one will work
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment
- [x] Create ECS task (not service) for reindexing Trellis into ElasticSearch (using `ld4p/sinopia_indexing_pipeline` container and `"command": ["bin/reindex"]`)
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment
- [x] Use CloudWatch Events to schedule running the reindex ECS task on a weekly basis (? see below) 
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment

ENV variables needed:
* `TRELLIS_BASE_URL`: URL of Trellis
* `BROKER_HOST`: Hostname of Amazon MQ
* `BROKER_PORT`: (STOMP) port for Amazon MQ
* `INDEX_HOST`: Hostname of ElasticSearch
* `INDEX_PORT`: Port of ElasticSearch

@jermnelson Is weekly the right frequency for complete reindexes? Too often? Not often enough? Those involve wiping the resource and template ES indices and then crawling Trellis to reindex all content.

**Comment by jermnelson** [comment]
> @jermnelson Is weekly the right frequency for complete reindexes? Too often? Not often enough? Those involve wiping the resource and template ES indices and then crawling Trellis to reindex all content.
No sure but running this weekly seems like a good idea. I would be interested in see the size, if any, of the divergence between Trellis and Elasticsearch.

**Comment by mjgiarlo** [comment]
@jermnelson should we re-assign this to @rsmith11? It's mostly (all?) Terraform work.

**Comment by rsmith11** [comment]
@mjgiarlo is there an endpoint once the container is up that I can have the ELB check to verify it's up and working?

**Comment by rsmith11** [comment]
When doing first run at an AWS deployment, the container seems to stop at `wait-on(41) waiting for: tcp://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614`

**Comment by mjgiarlo** [comment]
@rsmith11 the pipeline does not expose any endpoints. it's just a little node app that connects to other endpoints.

**Comment by mjgiarlo** [comment]
@rsmith11 :speech_balloon: 
> When doing first run at an AWS deployment, the container seems to stop at `wait-on(41) waiting for: tcp://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614`

the pipeline waits (up to 2m or 3m?) for Trellis, MQ, and ES to become available. that we're only seeing one line of output about waiting suggests to me that the container healthcheck is terminating the pipeline before it can make its connections. I am not sure what the healthcheck should be for the pipeline. Perhaps worth discussing in a meeting on Monday.

**Comment by rsmith11** [comment]
Trying to deploy in Dev, getting the following error:

```
> sinopia_indexing_pipeline@0.1.0 start /home/circleci
> babel-node runner.js
wait-on(40) waiting for: tcp:stomp+ssl://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
wait-on(40) timed out waiting for: tcp:stomp+ssl://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614; exiting with error
dependencies did not start up in time: Error: Timeout
connecting to stomp at stomp+ssl://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
events.js:174
throw er; // Unhandled 'error' event
^
Error: getaddrinfo ENOTFOUND stomp+ssl://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com stomp+ssl://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
at Socket.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:145:12)
at Socket.emit (events.js:189:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinopia_indexing_pipeline@0.1.0 start: `babel-node runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sinopia_indexing_pipeline@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/circleci/.npm/_logs/2019-05-23T17_16_03_014Z-debug.log
```

I can verify that systems in that IP range can talk to the AmazonMQ service on port 61614:

```
[ec2-user@ip-10-0-66-242 ~]$ telnet b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com 61614
Trying 10.0.64.152...
Connected to b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com.
Escape character is '^]'.
```

**Comment by mjgiarlo** [comment]
@rsmith11 could you try tweaking the value of `BROKER_HOST` from `stomp+ssl://b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com` to `b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com`

**Comment by rsmith11** [comment]
Got a little bit further:

```
> sinopia_indexing_pipeline@0.1.0 start /home/circleci
> babel-node runner.js
wait-on(40) exiting successfully found all: tcp:vpc-sinopia-es-development-vzugklhwtqspgqusnelnmlga6m.us-west-2.es.amazonaws.com:443, tcp:b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
connecting to stomp at b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
events.js:174
throw er; // Unhandled 'error' event
^
Error: No such command
at StompFrameEmitter.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:232:14)
at StompFrameEmitter.emit (events.js:189:13)
at StompFrameEmitter.error (/home/circleci/node_modules/stomp-client/lib/parser.js:62:8)
at StompFrameEmitter.parseCommand (/home/circleci/node_modules/stomp-client/lib/parser.js:71:14)
at StompFrameEmitter.handleData (/home/circleci/node_modules/stomp-client/lib/parser.js:36:12)
at Socket.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:188:18)
at Socket.emit (events.js:189:13)
at addChunk (_stream_readable.js:284:12)
at readableAddChunk (_stream_readable.js:265:11)
at Socket.Readable.push (_stream_readable.js:220:10)
Emitted 'error' event at:
at StompFrameEmitter.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:236:10)
at StompFrameEmitter.emit (events.js:189:13)
[... lines matching original stack trace ...]
at Socket.Readable.push (_stream_readable.js:220:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinopia_indexing_pipeline@0.1.0 start: `babel-node runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sinopia_indexing_pipeline@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/circleci/.npm/_logs/2019-05-23T20_51_31_792Z-debug.log
```

**Comment by mjgiarlo** [comment]
@rsmith11 Ah, I believe this may be caused by Amazon MQ requiring TLS, and the pipeline not using TLS. This should help:

https://github.com/LD4P/sinopia_indexing_pipeline/pull/20

Once that is merged, the container should be updated shortly thereafter.

**Comment by rsmith11** [comment]
Redeployed, and now getting invalid username/password.  Perhaps we need to pass it similar to trellis, where we pass it TRELLIS_NOTIFICATIONS_USERNAME and TRELLIS_NOTIFICATIONS_PASSWORD?

```
> sinopia_indexing_pipeline@0.1.0 start /home/circleci
> babel-node runner.js
wait-on(29) exiting successfully found all: tcp:vpc-sinopia-es-development-vzugklhwtqspgqusnelnmlga6m.us-west-2.es.amazonaws.com:443, tcp:b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
connecting to stomp at b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
events.js:174
throw er; // Unhandled 'error' event
^
Error: User name [] or password is invalid.
at StompFrameEmitter.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:223:14)
at StompFrameEmitter.emit (events.js:189:13)
at StompFrameEmitter.parseBody (/home/circleci/node_modules/stomp-client/lib/parser.js:136:12)
at StompFrameEmitter.handleData (/home/circleci/node_modules/stomp-client/lib/parser.js:42:12)
at TLSSocket.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:188:18)
at TLSSocket.emit (events.js:189:13)
at addChunk (_stream_readable.js:284:12)
at readableAddChunk (_stream_readable.js:265:11)
at TLSSocket.Readable.push (_stream_readable.js:220:10)
at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
at StompFrameEmitter.<anonymous> (/home/circleci/node_modules/stomp-client/lib/client.js:226:10)
at StompFrameEmitter.emit (events.js:189:13)
[... lines matching original stack trace ...]
at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinopia_indexing_pipeline@0.1.0 start: `babel-node runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sinopia_indexing_pipeline@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/circleci/.npm/_logs/2019-05-23T23_25_23_654Z-debug.log
```

**Comment by mjgiarlo** [comment]
@rsmith11 Ah. I'll give that a shot.

**Comment by mjgiarlo** [comment]
@rsmith11 https://github.com/LD4P/sinopia_indexing_pipeline/pull/21

**Comment by mjgiarlo** [comment]
@rsmith11 The updated container is now available. New env vars are `BROKER_USERNAME` and `BROKER_PASSWORD`.

**Comment by rsmith11** [comment]
Cloudwatch logs look good.  No errors.

**Comment by rsmith11** [comment]
Moving on to the task of reindexing, when running that task I'm seeing:

`error recreating indices: Bad Request :: {"path":"/_all","query":{},"statusCode":400,"response":"<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n</body>\r\n</html>\r\n"}`

**Comment by rsmith11** [comment]
After updating pipeline container, now seeing timeout error:

```
> babel-node runner.js
wait-on(29) waiting for: vpc-sinopia-es-development-vzugklhwtqspgqusnelnmlga6m.us-west-2.es.amazonaws.com:443
wait-on(29) timed out waiting for: vpc-sinopia-es-development-vzugklhwtqspgqusnelnmlga6m.us-west-2.es.amazonaws.com:443; exiting with error
dependencies did not start up in time: Error: Timeout
connecting to stomp at b-02f803b0-e82b-4f93-b480-fe61e69fcbb2-1.mq.us-west-2.amazonaws.com:61614
subscribing to /queue/trellis, waiting for messages

```

**Comment by mjgiarlo** [comment]
@rsmith11 	hmmm, is the branch you're working from pushed anywhere? and how about we pair on this on tuesday?

**Comment by rsmith11** [comment]
It's in the terraform-aws repo under the branch `sinopia-pipeline`

**Comment by mjgiarlo** [comment]
@rsmith11 looks like the index URL is missing the https:// prefix.

**Comment by mjgiarlo** [comment]
@rsmith11 	do you know what `${aws_elasticsearch_domain.es.endpoint}` evaluates to?

**Comment by rsmith11** [comment]
Adding https got it working.  Thanks!

**Comment by mjgiarlo** [comment]
@rsmith11 	awesome! What else needs to be done before closing this issue? cc: @jermnelson

**Comment by jermnelson** [comment]
I'm fine with closing this issue but will defer to @rsmith11
