### ISSUE TITLE
indexing breaks (Intermittent Indexing Problems with ActiveMQ)

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_indexing_pipeline#189]
paired w/ @jermnelson briefly just now to discuss two apparent problems:
* it appears that automatic indexing of created/modified resources in trellis isn't triggering the (re-)indexing of those resources.  it looks like the last successful indexing of a resource happened sometime yesterday, though stage is being actively used today (so we'd expect stuff to be getting indexed today).
* it also appears that we can't successfully manually run the reindexing task.

neither jeremy nor i were able to glean much helpful info from the logs on AWS console.  we did see something about a network error in the indexer logs, but it was unclear whether the error was from an attempt to connect to trellis (to fetch the resource) or to elastic search (to push the indexing document created from the resource into elastic search).

it would probably help to have someone who's more fluent with AWS debugging to help troubleshoot this.

@jermnelson might be able to post some illustrative log text or log screenshots from what he's found so far.

this is impacting cataloging work -- though the error is happening on stage, that's where people go to experiment with data that they will then create on prod.

corrections welcome from @jermnelson or anyone else if i've mis-characterized anything.

**Comment by jermnelson** [comment]
From the Active MQ log:
```2020-03-19 19:26:52,146 | WARN  | Transport Connection to: tcp://10.0.65.208:59600 failed: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake | org.apache.activemq.broker.TransportConnection.Transport | ActiveMQ Transport: ssl:///10.0.65.208:59600```

This is what we're seeing on the reindex task log that I started this morning:
```

18:53:05
error indexing: Request timed out
error indexing: Request timed out

18:53:05
https://trellis.stage.sinopia.io/repository/harvard/a6917ff4-f1c4-42c6-8e68-4742e563f9b2 contains
https://trellis.stage.sinopia.io/repository/harvard/a6917ff4-f1c4-42c6-8e68-4742e563f9b2 contains 
```

**Comment by jmartin-sul** [comment]
notes from how this got fixed yesterday:
* @justinlittman re-ran the reindex task manually and it succeeded that time.  we suspect either transient network error or some sort of operator error that we missed being the cause for prior failures on that front.
* we restarted trellis, so that it could get a good connection to ActiveMQ again, and then created and modified resources began automatically showing up in the index again as expected.

we suspect the issue is ActiveMQ flakiness, and will keep an eye on this issue to try and track further occurrences of it.  based on how much trouble it's causing us, we'll evaluate looking at ActiveMQ replacement options in the next sinopia WC (but as of standup today, we suspected that might not be worth the effort).

**Comment by jermnelson** [comment]
Here is the current remediation [steps](https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/sinopia/operations-concerns.md#indexing-problem) in DevOpsDocs.

**Comment by jermnelson** [comment]
Here are the documented incidences of this error:

-  2020-05-16 in production
-  2020-05-13 in stage
-  2020-03-25 in development
-  2020-03-18 in stage
-  2020-01-22 in production

**Comment by jermnelson** [comment]
Until PR https://github.com/LD4P/sinopia_editor/pull/2326 is merged and migrated to stage and production, we have decided as a short-term fix to create a re-index task to run every half-hour in stage and production. See https://github.com/sul-dlss/operations-tasks/issues/2339.

**Comment by jermnelson** [comment]
With move to MongoDB/DocumentDB, will close this issue once all three environments are on the same version and no longer using ActiveMQ.

**Comment by jermnelson** [comment]
Finally closing this issue with Production now on version `3.4.1` and we are no longer using Trellis or ActiveMQ.

**Comment by justinlittman** [comment]
NICE
