### ISSUE TITLE
Determine ElasticSearch size

### ISSUE THREAD

**Issue by rsmith11** [LD4P/sinopia_indexing_pipeline#23]
Back when the project first started, little was known about how much storage the ElasticSearch setup would take in AWS.  It was decided to initially set it to 20G.  Now that it is in use, it would be good to review this size and determine if more storage is needed.

**Comment by michelleif** [comment]
@jermnelson @rsmith11 can we postpone this to next work cycle?

**Comment by rsmith11** [comment]
Increased to 40G in dev with no issues.  Will be pushing to stage/prod later.

**Comment by jermnelson** [comment]
@rsmith11 can we close this issue?
