### ISSUE TITLE
Delete error

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_indexing_pipeline#242]
![image](https://user-images.githubusercontent.com/588335/97208528-973d3600-1791-11eb-956b-15d1f9327138.png)

It appears that the doc is not provided.

**Comment by justinlittman** [comment]
However, indexer requires the doc: https://github.com/LD4P/sinopia_indexing_pipeline/blob/main/src/Indexer.js#L85

See also https://github.com/LD4P/sinopia_indexing_pipeline/blob/main/src/Pipeline.js

**Comment by jcoyne** [comment]
How does one reproduce this error?

**Comment by justinlittman** [comment]
To reproduce locally (with Docker):
1. Create a resource and get URI.
2. Observe the indexing pipeline: `docker compose logs -f pipeline`
3. `curl -X DELETE <URI>`

**Comment by justinlittman** [comment]
Fixing this ticket is going to be tricky. All that is provided in the delete message is the Mongo id. However, we currently don't index the Mongo id. To fix this issue, we're going to have to additionally index the Mongo id so that it can be used for deleting.
