### ISSUE TITLE
Newly created templates with incorrect Date format are not showing in Resource Templates list

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_indexing_pipeline#285]
**Action required for this ticket**:
When indexing, a date that does not parse should be ignored; indexing should not fail.

Additional context:
when creating a template, the Date field is optional, and expects a literal like yyyy-mm-dd

but if you mistakenly enter the date in a different format like mm-dd-yyyy, then the template saves successfully, but does not show up in the Resource Templates list, even though the template URI works

examples on stage:
https://api.stage.sinopia.io/resource/demo:art:object (date was entered as 07-18-2021)
https://api.stage.sinopia.io/resource/x:y:z (date was entered as 07-18-2021)
https://api.stage.sinopia.io/resource/random:this2 (date was entered as `this is a date`)

none of these templates are findable on the Resource Templates page

side note: if you edit an existing template, one that has either a correctly formatted date or no date at all, and you enter an incorrectly formatted date, the template will still appear in the Resource Templates page (the date is not displayed but that's fine). example on stage:
https://api.stage.sinopia.io/resource/random:this3 (originally created without a date, then added a correctly formatted date, then edited again to make the date `yesterday`)

possible solutions:
- LD4P/sinopia_editor#2727 or
- if LD4P/sinopia_editor#2727 is not implemented: when date is entered incorrectly, display template in Resource Templates list anyway

**Comment by NancyL** [comment]
This seems to be part of a broader question about how and when we enforce date formats.

**Comment by michelleif** [comment]
@justinlittman if we implement #2889 and #2890, and specify that the datatype of template Date field is EDTF, will that fix the problem? does the indexing pipeline accept any EDTF date?

**Comment by NancyL** [comment]
Adding some verbal instruction to adhere to EDTF would be good in addition to the actual datatype itself.

**Comment by michelleif** [comment]
@justinlittman is the solution to enforce what dates are entered, or to change how the indexing pipeline deals with the data in this field?

**Comment by justinlittman** [comment]
Both, but fix the indexing pipeline first.
