### ISSUE TITLE
display the rdfs:label that is the object of the resource in search results, not any other rdfs:label from the resource

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_indexing_pipeline#321]
per #315: 

> If a resource has an rdfs:label, it should be indexed as the label. The rdfs:label should be preferred over a label constructed from the title

the above was with the assumption that a resource could have a single field with the http://www.w3.org/2000/01/rdf-schema#label property, which cataloger could fill in as a label, especially for resources without one of the things we used to treat as label for search results, like title

but...many resources end up with several http://www.w3.org/2000/01/rdf-schema#label properties in their RDF, and those are not necessarily intended to be the label of the entire resource

this change is producing unwanted results. for example:
https://api.stage.sinopia.io/resource/b0319047-acd0-4f30-bd8b-98e6c1bac6b0

has several http://www.w3.org/2000/01/rdf-schema#label properties. it also has title properties. user is expecting to see this resource listed with its title, like did in the past, but instead one of the labels is being used
![Screen Shot 2021-10-01 at 3.54.17 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/c30956e2-d230-43fd-9f8f-16e4f102f2fa)

here's a related example on DEV; this resource doesn't have a title, but it does have more than one http://www.w3.org/2000/01/rdf-schema#label:
https://api.development.sinopia.io/resource/0b612117-9c2c-4eff-ac37-53b1b6f081f4

`label45` is the label that goes with a URI, and ends up being the one used in search results, but `labelxyz` is the one that is the object of the sort of field this feature was designed for, a simple field that says <thisresource> <haslabel> <label>.
![Screen Shot 2021-10-01 at 4.06.16 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/1a778fde-0479-43d7-a2d4-b9e9f3a9eed8)

i've done some testing but i can't figure out why Sinopia is preferring `label45` to `labelxyz` as it doesn't seem consistent from resource to resource.

if there's more than one http://www.w3.org/2000/01/rdf-schema#label in a resource, which one is getting indexed as used as label in search results and elsewhere?

**Comment by michelleif** [comment]
@gdegroat@stanford.edu

**Comment by NancyL** [comment]
ay yes, I found that I am getting the label for a bf:contents when entering the URI for a bf:Work in the Instance template


![image](https://user-images.githubusercontent.com/5078198/135698013-85b79761-9119-4d12-91b6-afd97a979472.png)

Not sure if it's related, but some of the labels set as defaults were not coming through. When I looked in the template, they had been turned into URIs. 
![image](https://user-images.githubusercontent.com/5078198/135698134-70dac80c-2d6e-4821-8797-777c153adf6b.png)

**Comment by michelleif** [comment]
woudl this fix it: index rdfs:label **only** if statement is <resourceuri> <rdfs:label> <label>; don't use any other labels as "the label" (but still index them so they can be found by searching)

**Comment by NancyL** [comment]
So this is affecting both work and instance titles--the URI for the work I entered has a label from the contents, and the URI for the instance has a label from a general note. See entries 1 & 3 below:
![image](https://user-images.githubusercontent.com/5078198/135762964-9887cbe1-4324-47b0-a36a-1395553c5efd.png)
I'm wondering if the URI & label coupling is broken?

**Comment by NancyL** [comment]
On the other hand, the resulting rdf as seen from the template and the conversion to MARC have everything in the right place! So it seems limited to the search/display aspect.
MARC conversion of previous example:
![image](https://user-images.githubusercontent.com/5078198/135763319-44d9240b-efcd-4ef3-9709-65b9525a7f20.png)

**Comment by jermnelson** [comment]
The expected indexing behavior is use the `rdfs:label` associated with the root resource and not any `rdfs:label` that may contained within the resource's RDF due to embedded templates.

**Comment by michelleif** [comment]
there are also rdfs:labels associated with any URI or lookup field, even if not embedded. these should not be indexed as "the label" shown in search results, but they should be indexed for searchability

**Comment by michelleif** [comment]
this might need fixin as well: https://github.com/LD4P/sinopia_editor/issues/3026

**Comment by NancyL** [comment]
bf:title > Title does not have an rdfs:label in the template. It is bf:mainTitle. There is a request to auto-add an rdfs:label for title based on the the bf:mainTitle, etc.

**Comment by michelleif** [comment]
if there's no label, we will still display the title (this page lists all the properties that are considered "title").

**Comment by NancyL** [comment]
can you give me the link to the page listing the properties?

**Comment by michelleif** [comment]
sorry it's https://github.com/LD4P/sinopia/wiki/Searching-in-Sinopia (fixed comment above too)

**Comment by michelleif** [comment]
rewriting to better explain problem, as https://github.com/LD4P/sinopia_editor/issues/3096
