### ISSUE TITLE
when searching Sinopia, search string should match strings with same letters plus diacritics

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_indexing_pipeline#53]
see LD4P/sinopia_editor#1265 and LD4P/sinopia_editor#1219 for examples

**Comment by jmartin-sul** [comment]
@justinlittman will do the reindexing part when he deploys on friday.  closing this for now, we can re-open if search is still diacritic sensitive after that deployment and the subsequent reindexing.
