### ISSUE TITLE
Index everything

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_indexing_pipeline#89]
That is, every resource. If there is not a title available to use as the label, use the URI.

**Comment by michelleif** [comment]
once this is done, does this mean we can search for *any* Sinopia resource by its Trellis URI on the Search tab?

**Comment by justinlittman** [comment]
Yes. Bonus.

**Comment by michelleif** [comment]
Woot

**Comment by mjgiarlo** [comment]
@justinlittman This is how the pipeline used to behave before https://github.com/LD4P/sinopia_indexing_pipeline/issues/34, right?

**Comment by justinlittman** [comment]
closed by #93
