### ISSUE TITLE
when search finds RDA title, use that as the label in the search results instead of the URI

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_indexing_pipeline#98]
#94 added indexing of RDA titles properties

but when I search for a word that is in a value that's the object of one of these title properties, the search result shows me the URI of the resource as the label, instead of the title

in DEV, search: `hazard`
this finds https://trellis.development.sinopia.io/repository/washington/06ee1b9e-f8ab-444b-974a-2fa193e3f6e9
which has one of the indexed RDA title properties (has preferred title of work: http://rdaregistry.info/Elements/w/P10223)
whose value is: _What factors influence the quality of hazard mitigation plans in Washington State?_ 
<img width="1264" alt="Screen Shot 2019-10-30 at 10 02 40 PM" src="https://user-images.githubusercontent.com/23069165/67920547-dc6c5f00-fb61-11e9-8180-f16228bf4f76.png">

so Title in search results should show "What factors influence the quality of hazard mitigation plans in Washington State?"
but instead it shows the resource URI
<img width="983" alt="Screen Shot 2019-10-30 at 10 02 16 PM" src="https://user-images.githubusercontent.com/23069165/67920539-d5455100-fb61-11e9-8be0-8197a330c48f.png">

**Comment by justinlittman** [comment]
I re-indexed in development; try now.

**Comment by michelleif** [comment]
All good now
